
set -g @plugin 'tmux-plugins/tpm' # mandatory
set -g @plugin 'tmux-plugins/tmux-sensible' # optional recommended

# set desired theme options...
set -g status-position bottom
set -s escape-time 0
set -g focus-events on 
set -g mouse

run '~/.tmux/plugins/tpm/tpm'
